### PR TITLE
add checkbox toggles for each contrast type

### PR DESCRIPTION
**Pull request by matteszk**
Adding ability to turn off all DNP combo swatches so that they don't visually clutter the useable combos when making design decisions. There's a checkbox for each type (aaa, aa, aa18, dnp) incase someone wants to increase specificity of their useable combos.

### CODE REVIEW

**Comment by kevinmpowell** [comment]
@matteszk thanks for this! I'll take a look later this week and roll it in if it all looks good.

**Comment by astranchet** [comment]
Hello, I would love this feature to go live! Are you planning to merge sometimes?

**Comment by Veyfeyken** [comment]
+1 on the merge request

**Comment by pushingvision** [comment]
+1 on the merge request! This would be so helpful

**Comment by astranchet** [comment]
@Veyfeyken @pushingvision I've deployed it on https://a11y-contrast-grid.netlify.app/ for personal use 😅

**Comment by pushingvision** [comment]
@astranchet Wonderful! Thank you so much!

**Comment by sbeatty900** [comment]
+1 on this PR, but also would be great if it could reference the filter state from URL params. That way, you can disable "DNP" and use that as a link that would hide DNP when the page loads for initial view.

**Comment by kevinmpowell** [comment]
@matteszk this is _finally_ merged. Only took four years 😉 

Thanks for contributing this feature, @astranchet thanks for bridging the gap in the meantime and @sbeatty900 thanks for the suggestion to make sure this works persistently with the URL.

Cool to see people using this tool after all these years.

**Comment by sbeatty900** [comment]
Fantastic! Thanks so much for taking the time to incorporate this. We are planning to use on a brand standards site to help people better understand accessible color contrast. Lots of tools out there now, but this was def my favorite so thanks for making it even better.

**Comment by astranchet** [comment]
@kevinmpowell the tool is now even better, thanks a lot for taking the time!

**Pull request merged**
